import ast
import re


FORBIDDEN_PATTERNS = [
    r"\bDROP\s+TABLE\b",
    r"\bDROP\s+DATABASE\b",
    r"\bTRUNCATE\b",
    r"\bDELETE\s+FROM\b",
    r"\bALTER\s+TABLE\b",
    r"\bos\.system\b",
    r"\bsubprocess\b",
    r"\beval\s*\(",
    r"\bexec\s*\(",
]


def validate_script(source: str) -> dict:
    issues: list[str] = []
    syntax_ok = True
    lint_ok = True
    safety_ok = True

    if not source.strip():
        return {
            "valid": False,
            "syntax_ok": False,
            "lint_ok": False,
            "safety_ok": False,
            "issues": ["Script is empty"],
        }

    try:
        ast.parse(source)
    except SyntaxError as exc:
        syntax_ok = False
        issues.append(f"Syntax error: {exc.msg} (line {exc.lineno})")

    for pattern in FORBIDDEN_PATTERNS:
        if re.search(pattern, source, re.IGNORECASE):
            safety_ok = False
            issues.append(f"Forbidden pattern detected: {pattern}")

    if "DATABASE_URL" not in source and "create_engine" in source:
        lint_ok = False
        issues.append("Use DATABASE_URL environment variable for database connections")

    valid = syntax_ok and safety_ok and lint_ok
    return {
        "valid": valid,
        "syntax_ok": syntax_ok,
        "lint_ok": lint_ok,
        "safety_ok": safety_ok,
        "issues": issues,
    }


def build_readme_snippet(*, session_id: int, user_email: str, model_used: str) -> str:
    return f"""# Data Cleaning Script — Execution Guide

Generated by Health Research Assistant
Session ID: {session_id}
Author: {user_email}
Model: {model_used}

## Prerequisites
- Python 3.11+
- pandas, SQLAlchemy, psycopg2-binary (or appropriate DB driver)
- Approved database access in a secure environment

## Setup
```bash
export DATABASE_URL="postgresql://user:pass@host:5432/dbname"
pip install pandas sqlalchemy psycopg2-binary
```

## Run
```bash
python data_clean.py
```

## Important
- Review the script with your data engineering team before production use.
- Never run unreviewed scripts against production databases.
- Ensure compliance with your institution's data governance policies.
"""
