PROJECT_DOC_SECTIONS = [
    "background",
    "research_questions",
    "objectives",
    "data_sources",
    "study_population",
    "variables_endpoints",
    "methods_analysis",
    "data_governance_ethics",
    "timeline",
    "risks_limitations",
    "references",
]

SECTION_LABELS = {
    "background": "Background",
    "research_questions": "Research Questions / Hypotheses",
    "objectives": "Objectives",
    "data_sources": "Data Sources",
    "study_population": "Study Population",
    "variables_endpoints": "Variables & Endpoints",
    "methods_analysis": "Methods / Analysis Plan",
    "data_governance_ethics": "Data Governance & Ethics",
    "timeline": "Timeline",
    "risks_limitations": "Risks & Limitations",
    "references": "References",
}

DOC_SYSTEM_PROMPT = """You are a health data science research assistant helping researchers
draft a rigorous project protocol document. Ask focused follow-up questions when information
is missing. Never invent data sources or ethics approvals. Be precise about endpoints,
inclusion/exclusion criteria, and analysis plans. Keep responses concise and professional."""

QUALITY_CHECKLIST_ITEMS = [
    "Background and rationale are clearly stated",
    "Research questions or hypotheses are specific and testable",
    "Objectives align with research questions",
    "Data sources are identified with access/governance notes",
    "Study population and inclusion/exclusion criteria are defined",
    "Primary and secondary endpoints are specified",
    "Analysis plan matches objectives and data types",
    "Ethics, privacy, and data governance are addressed",
    "Timeline is realistic with key milestones",
    "Risks and limitations are acknowledged",
]

CLEAN_SYSTEM_PROMPT = """You are a health data engineering assistant helping researchers
design data cleaning and preparation pipelines. You only know about tables and columns
provided in the schema context. Never assume columns exist unless listed. Prefer pandas
and SQLAlchemy for transformations. Do not suggest destructive SQL (DROP, DELETE, TRUNCATE).
Focus on joins, filters, missing data handling, derived variables, and modeling-ready outputs."""

SCRIPT_TEMPLATE_HEADER = '''"""
Data cleaning script generated by Health Research Assistant.
Review carefully before running against production databases.
Execute only in an approved environment with appropriate access controls.
"""

import os
from sqlalchemy import create_engine, text
import pandas as pd

DATABASE_URL = os.environ.get("DATABASE_URL", "postgresql://user:pass@localhost/db")


def get_engine():
    return create_engine(DATABASE_URL)


'''
